version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "4306:3306"
    volumes:
      - mysql-data:/var/lib/mysql #データ永続化
    env_file: db.env

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app_name
      - gem_data:/usr/local/bundle  #gemを永久化
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: db.env

volumes:
  mysql-data:
  gem_data: